export const TYPES = {
	CREATE_WINE: "CREATE_WINE",
	EDIT_WINE: "EDIT_WINE",
	APPEND_WINE: "APPEND_WINE",
	DELETE_WINE: "DELETE_WINE",
	SET_WINES: "SET_WINES",
	CLEAR_WINES: "CLEAR_WINES",
	SET_ALL_WINES: "SET_ALL_WINES",
};