export const TYPES = {
  CLEAR_WINES: "CLEAR_WINES",
  DELETE_WINE: "DELETE_WINE",
  SET_ALL_WINES: "SET_ALL_WINES",
  SET_WINES: "SET_WINES",
  CONFIRM_REGISTERED: "CONFIRM_REGISTERED",
  RESET_REGISTERED: "RESET_REGISTERED"
};
